### ISSUE TITLE
Loading ImageNet dataset

### ISSUE THREAD

**Issue by SanghyeokSon** [bhrqw/AttriCLIP#3]
Most of all, thank you for sharing your exciting research.

I have one question regarding the ImageNet dataloader. 
While loading ImageNet data, I encountered an out-of-range error in line 232 of /dataset/incremental_dataloader.py

I think the cause of the error is that the target value of train_dataset is 0-999.
How do I fix the problem?

Sincerely,

**Comment by linlany** [comment]
I also have this problem, and the class order is not provided

**Comment by bhrqw** [comment]
Thank you for your interest in our work. We added code to create the Imagenet_100 dataset. You can build the corresponding dataset and then run main_incremental_ima.py.

**Comment by SanghyeokSon** [comment]
Thank you so much for your quick response. But I'm still having the same problem. 
In incremental_dataloader.py on line 286, train_dataset.targets has a value of 0-999, which causes an out-of-range error in the following lines.
